import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Karen Litwinczyk
 */
public class FoodLog extends javax.swing.JFrame {
    //makes a new instance of mainWindow and FileWriter
    private MainWindow mw;
    private FileWriter fw;
    /**
     * Creates new form FoodLog
     */
    public FoodLog() {
        initComponents();
    }
    //function that sets the main window to the instance of what the user passes in
    public void setMainWindow(MainWindow m){
        this.mw = m;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfMeal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfSnack = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        addBreakfastBtn = new javax.swing.JButton();
        addLunchBtn = new javax.swing.JButton();
        addDinnerBtn = new javax.swing.JButton();
        cancelBtnFood = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("Meal:");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Snack:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Date:");

        addBreakfastBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addBreakfastBtn.setText("BreakFast");
        addBreakfastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBreakfastBtnActionPerformed(evt);
            }
        });

        addLunchBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addLunchBtn.setText("Lunch");
        addLunchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLunchBtnActionPerformed(evt);
            }
        });

        addDinnerBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addDinnerBtn.setText("Dinner");
        addDinnerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDinnerBtnActionPerformed(evt);
            }
        });

        cancelBtnFood.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        cancelBtnFood.setText("CANCEL");
        cancelBtnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnFoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfDate, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfSnack)
                    .addComponent(jtfMeal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(addBreakfastBtn)
                        .addGap(18, 18, 18)
                        .addComponent(addLunchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(addDinnerBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtnFood)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jtfSnack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jtfMeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBreakfastBtn)
                    .addComponent(addLunchBtn)
                    .addComponent(addDinnerBtn))
                .addGap(20, 20, 20)
                .addComponent(cancelBtnFood)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLunchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLunchBtnActionPerformed
        // TODO add your handling code here:
        //sets this window's visibility to false and shows mainWindow
        this.setVisible(false);
        mw.setVisible(true);
        //writes the text in the text fields to the text file 
        FileWriter fw;
        try {
            fw = new FileWriter("FitnessLog.txt", true);
            fw.write(jtfDate.getText() + "\n");
            fw.write("Lunch: " + jtfMeal.getText() + "\n");
            fw.write("Snack: " + jtfSnack.getText() + "\n");
            fw.close();
            
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addLunchBtnActionPerformed

    private void cancelBtnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnFoodActionPerformed
        // TODO add your handling code here:
        //sets mainWindows's visibility to true and sets this window's visibility to false
        this.setVisible(false);
        mw.setVisible(true);
    }//GEN-LAST:event_cancelBtnFoodActionPerformed

    private void addBreakfastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBreakfastBtnActionPerformed
        // TODO add your handling code here:
        //shows mainWindow, hides this window
        this.setVisible(false);
        mw.setVisible(true);
        //writes the data from the text fields into the text file
        FileWriter fw;
        try {
            fw = new FileWriter("FitnessLog.txt", true);
            fw.write(jtfDate.getText() + "\n");
            fw.write("Breakfast: " + jtfMeal.getText() + "\n");
            fw.write("Snack: " + jtfSnack.getText() + "\n");
            fw.close();
            
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addBreakfastBtnActionPerformed

    private void addDinnerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDinnerBtnActionPerformed
        // TODO add your handling code here:
        //hides this window and shows the main window 
        this.setVisible(false);
        mw.setVisible(true);
        //writes the data from the text fields into the text file
        FileWriter fw;
        try {
            fw = new FileWriter("FitnessLog.txt", true);
            fw.write(jtfDate.getText() + "\n");
            fw.write("Dinner: " + jtfMeal.getText() + "\n");
            fw.write("Snack: " + jtfSnack.getText() + "\n");
            fw.close();
            
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addDinnerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBreakfastBtn;
    private javax.swing.JButton addDinnerBtn;
    private javax.swing.JButton addLunchBtn;
    private javax.swing.JButton cancelBtnFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfMeal;
    private javax.swing.JTextField jtfSnack;
    // End of variables declaration//GEN-END:variables
}
