import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karen Litwinczyk
 */
public class LogWaterWindow extends javax.swing.JFrame {
    //makes an instance of mainWindow
    private MainWindow mw;
    /**
     * Creates new form LogWaterWindow
     */
    public LogWaterWindow() {
        initComponents();
    }
    //sets the mainwindow to the instance of what the user sends it
    public void setMainWindow(MainWindow m){
        this.mw = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDateWater = new javax.swing.JLabel();
        jlWaterOz = new javax.swing.JLabel();
        addBtnWater = new javax.swing.JButton();
        cancelBtnWater = new javax.swing.JButton();
        jtfDate = new javax.swing.JTextField();
        jtfOzWater = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlDateWater.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jlDateWater.setText("Date:");

        jlWaterOz.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jlWaterOz.setText("Ounces Of Water:");

        addBtnWater.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addBtnWater.setText("ADD");
        addBtnWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnWaterActionPerformed(evt);
            }
        });

        cancelBtnWater.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        cancelBtnWater.setText("CANCEL");
        cancelBtnWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnWaterActionPerformed(evt);
            }
        });

        jtfOzWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOzWaterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelBtnWater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtnWater))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlDateWater)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlWaterOz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfOzWater, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlDateWater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlWaterOz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfOzWater))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtnWater)
                    .addComponent(cancelBtnWater))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnWaterActionPerformed
        // TODO add your handling code here:
        //hides this window and shows mainWindow
        this.setVisible(false);
        mw.setVisible(true);
    }//GEN-LAST:event_cancelBtnWaterActionPerformed

    private void jtfOzWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOzWaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOzWaterActionPerformed

    private void addBtnWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnWaterActionPerformed
        // TODO add your handling code here:
        //hides this window 
        this.setVisible(false);
        mw.setVisible(true);
        //makes new instance of FileWriter and writes the data from the text fields into the text file
        FileWriter fw;
        try {
            fw = new FileWriter("FitnessLog.txt", true);
            fw.write(jtfDate.getText() + "\n");
            fw.write("Ounces of Water: " + jtfOzWater.getText() + "\n");
            fw.close();
            
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_addBtnWaterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogWaterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogWaterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogWaterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogWaterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogWaterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtnWater;
    private javax.swing.JButton cancelBtnWater;
    private javax.swing.JLabel jlDateWater;
    private javax.swing.JLabel jlWaterOz;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfOzWater;
    // End of variables declaration//GEN-END:variables
}
