
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karen Litwinczyk
 */
public class MainWindow extends javax.swing.JFrame {
    //creates a new instance of the WorkOutWindow class
    WorkoutLogWindow woWin;
    //creates a new instance of the Timer Window class
    TimerWindow tw;
    //creates a new instance of the FoodLog class
    FoodLog fl;
    //creates a new instance of the LogWaterWindow class
    LogWaterWindow lw;
    //a string to keep track of the user's name.
    String name;
    
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        //makes a popUp window asking the user to enter in their name
        this.name = JOptionPane.showInputDialog("Please Enter in your name.");
        //this sets the label on the main screen to the user's name
        jlName.setText("Name: " + this.name);
        //initializes the new instance and hides it
        woWin = new WorkoutLogWindow();
        woWin.setVisible(false);
        //initializes the new instance and hides it
        tw = new TimerWindow();
        tw.setVisible(false);
        //initializes the new instance and hides it
        fl = new FoodLog();
        fl.setVisible(false);
        //initializes the new instance and hides it
        lw = new LogWaterWindow();
        lw.setVisible(false);
        //creates a new instance of the FileWriter class
        FileWriter fw;
        try {
            //initializes the new instance and adds the text to the file (appends it does not clear it)
            fw = new FileWriter("FitnessLog.txt", true);
            fw.write("HELLO " + name + "! Here is your Fitness log for today!\n");
            fw.close();
        //catches errors/exceptions raised if at all    
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    } 
   
//    public static void main(String args[]){
//        MainWindow main = new MainWindow();
//    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workoutLogBtn = new javax.swing.JButton();
        foodLogBtn = new javax.swing.JButton();
        waterIntakeBtn = new javax.swing.JButton();
        timerBtn = new javax.swing.JButton();
        jlName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workoutLogBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        workoutLogBtn.setText("Log Workout");
        workoutLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workoutLogBtnActionPerformed(evt);
            }
        });

        foodLogBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        foodLogBtn.setText("Log Food");
        foodLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodLogBtnActionPerformed(evt);
            }
        });

        waterIntakeBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        waterIntakeBtn.setText("Log Water");
        waterIntakeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterIntakeBtnActionPerformed(evt);
            }
        });

        timerBtn.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        timerBtn.setText("Timer");
        timerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerBtnActionPerformed(evt);
            }
        });

        jlName.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timerBtn)
                    .addComponent(workoutLogBtn)
                    .addComponent(waterIntakeBtn)
                    .addComponent(foodLogBtn))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(timerBtn)
                .addGap(18, 18, 18)
                .addComponent(foodLogBtn)
                .addGap(18, 18, 18)
                .addComponent(waterIntakeBtn)
                .addGap(18, 18, 18)
                .addComponent(workoutLogBtn)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workoutLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workoutLogBtnActionPerformed
        // TODO add your handling code here:
       //sets the main window invisible, shows the workout window window and 
       //sets the mainWindow (this) to the mainwindow variable/instance in workoutWindow
        this.setVisible(false);
        woWin.setVisible(true);
        woWin.setMainWindow(this);
    }//GEN-LAST:event_workoutLogBtnActionPerformed

    private void timerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerBtnActionPerformed
        // TODO add your handling code here:
        //sets the main window invisible, shows the timer window window and 
       //sets the mainWindow (this) to the mainwindow variable/instance in timerWindow
        this.setVisible(false);
        tw.setVisible(true);
        tw.setMainWindow(this);
    }//GEN-LAST:event_timerBtnActionPerformed

    private void foodLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodLogBtnActionPerformed
        // TODO add your handling code here:
        //sets the main window invisible, shows the foodLog window and 
       //sets the mainWindow (this) to the mainwindow variable/instance in foodLog
        this.setVisible(false);
        fl.setVisible(true);
        fl.setMainWindow(this);
    }//GEN-LAST:event_foodLogBtnActionPerformed

    private void waterIntakeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterIntakeBtnActionPerformed
        // TODO add your handling code here:
        //sets the main window invisible, shows the waterLog window and 
       //sets the mainWindow (this) to the mainwindow variable/instance in waterLog
        this.setVisible(false);
        lw.setVisible(true);
        lw.setMainWindow(this);
    }//GEN-LAST:event_waterIntakeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foodLogBtn;
    private javax.swing.JLabel jlName;
    private javax.swing.JButton timerBtn;
    private javax.swing.JButton waterIntakeBtn;
    private javax.swing.JButton workoutLogBtn;
    // End of variables declaration//GEN-END:variables
}
